import os
from typing import Dict, List, Tuple

SEARCH_KEYWORDS: List[str] = [
    "DevOps Engineer",
    "AWS Engineer",
    "AWS Cloud Engineer",
    "Cloud Engineer",
    "Platform Engineer",
    "Site Reliability Engineer",
    "SRE",
    "Infrastructure Engineer",
    "Kubernetes Engineer",
    "Terraform Engineer",
    "Cloud DevOps Engineer",
    "CI/CD Engineer",
    "Release Engineer",
]

LOCATIONS: List[str] = [
    "Pune, India",
    "Remote, India",
    "Mumbai, India",
    "Bengaluru, India",
    "Hyderabad, India",
    "Chennai, India",
    "Delhi NCR, India",
]

LOCATION_PRIORITY: Dict[str, int] = {
    "pune": 100,
    "remote": 80,
    "mumbai": 60,
    "bengaluru": 60,
    "bangalore": 60,
    "hyderabad": 60,
    "chennai": 50,
    "delhi ncr": 50,
    "delhi": 50,
    "gurgaon": 50,
    "noida": 50,
    "india": 20,
}

KEYWORD_BONUS: Dict[str, int] = {
    "aws": 20,
    "kubernetes": 20,
    "k8s": 20,
    "terraform": 15,
    "github actions": 15,
    "docker": 15,
    "ecs": 15,
    "eks": 15,
    "ci/cd": 10,
    "gitlab": 5,
    "ansible": 10,
    "jenkins": 10,
    "helm": 10,
    "istio": 10,
    "prometheus": 10,
    "grafana": 10,
    "pulumi": 10,
    "crossplane": 10,
    "argocd": 10,
    "argo": 10,
}

REQUEST_TIMEOUT: int = 15
MAX_RETRIES: int = 3
BACKOFF_BASE: float = 1.0

GREENHOUSE_BOARDS: Dict[str, str] = {
    "datadog": "datadog",
    "hashicorp": "hashicorp",
    "snowflake": "snowflake",
    "crowdstrike": "crowdstrike",
    "palobio": "palobio",
    "reddit": "reddit",
    "airbnb": "airbnb",
    "dropbox": "dropbox",
    "instacart": "instacart",
    "stripe": "stripe",
    "pinterest": "pinterest",
    "lyft": "lyft",
    "zoom": "zoom",
    "databricks": "databricks",
    "confluent": "confluent",
    "elastic": "elastic",
    "mongodb": "mongodb",
    "godaddy": "godaddy",
    "twilio": "twilio",
    "splunk": "splunk",
    "digitalocean": "digitalocean",
    "dbtlabs": "dbtlabs",
    "vercel": "vercel",
    "palantir": "palantir",
    "blend": "blend",
    "brex": "brex",
    "chime": "chime",
    "deel": "deel",
    "doordash": "doordash",
    "figma": "figma",
    "gem": "gem",
    "ginkgo": "ginkgo",
    "gitlab": "gitlab",
    "huntress": "huntress",
    "ironclad": "ironclad",
    "juniper": "juniper",
    "lattice": "lattice",
    "mapbox": "mapbox",
    "mural": "mural",
    "netskope": "netskope",
    "nextdoor": "nextdoor",
    "nvidia": "nvidia",
    "okta": "okta",
    "ontra": "ontra",
    "oracle": "oracle",
    "pexels": "pexels",
    "podia": "podia",
    "podium": "podium",
    "postman": "postman",
    "prisma": "prisma",
    "redfin": "redfin",
    "rippling": "rippling",
    "robinhood": "robinhood",
    "sendgrid": "sendgrid",
    "servicenow": "servicenow",
    "shopify": "shopify",
    "sift": "sift",
    "sonder": "sonder",
    "spotify": "spotify",
    "square": "square",
    "strava": "strava",
    "tegus": "tegus",
    "tiktok": "tiktok",
    "uber": "uber",
    "upstart": "upstart",
    "vensa": "vensa",
    "wealthfront": "wealthfront",
    "wework": "wework",
    "wish": "wish",
    "wiz": "wiz",
    "zapier": "zapier",
    "zendesk": "zendesk",
    "ziprecruiter": "ziprecruiter",
}

LEVER_SLUGS: List[str] = [
    "atlassian",
    "lumen",
    "nuro",
    "netsuite",
    "grammarly",
    "notion",
    "coinbase",
    "affirm",
    "redcanary",
    "algolia",
    "automattic",
    "calendly",
    "checkr",
    "coda",
    "discord",
    "drata",
    "fivetran",
    "flexport",
    "gusto",
    "hopin",
    "hubspot",
    "intercom",
    "launchdarkly",
    "loom",
    "messagebird",
    "monzo",
    "openai",
    "opencare",
    "parabola",
    "pexels",
    "plex",
    "replix",
    "segment",
    "sentry",
    "skyscanner",
    "smartcar",
    "snyk",
    "sorare",
    "spotify",
    "stackoverflow",
    "superhuman",
    "supreme",
    "tandem",
    "ted",
    "teleport",
    "tray",
    "trello",
    "typeform",
    "udemy",
    "venmo",
    "webflow",
    "weglot",
]

ASHBY_BOARDS: List[str] = [
    "anthropic",
    "linear",
    "raycast",
    "luko",
    "ashby",
]

SMTP_HOST: str = "smtp.gmail.com"
SMTP_PORT: int = 587

GMAIL_USERNAME: str = os.environ.get("GMAIL_USERNAME", "")
GMAIL_APP_PASSWORD: str = os.environ.get("GMAIL_APP_PASSWORD", "")
RECIPIENT_EMAIL: str = os.environ.get("RECIPIENT_EMAIL", "")

CSV_FILENAME: str = "devops_jobs_report_{date}.csv"
HTML_FILENAME: str = "devops_jobs_report_{date}.html"

USER_AGENTS: List[str] = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15",
]

MAX_JOBS_PER_SOURCE: int = 50
LOOKBACK_HOURS: int = 24
